name: Docker Image CI

#Eventi che triggerano la action
on:
  push:
    branches: [ main ]

#Cosa fare
jobs:

  build:
    #Macchina virtuale
    runs-on: ubuntu-latest

    steps:
    #Scarica questa repo
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    #Fa il login su Docker Hub con delle secrets della repo
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #Installa Buildx, plugin che estende le capacità del building di Docker Images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #Chache per ottimizzazione
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-
    #Data corrente per il tag
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%y%m%d.%I%M%S)"
    #Costruisce l'immagine Docker e fa il push
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/formula1data:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/formula1data:${{ steps.date.outputs.date }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
