name: Docker Image CI

#Eventi che triggerano la action
on:
  push:
    branches: [ main ]

#Cosa fare
jobs:

  build:
    #Macchina virtuale
    runs-on: ubuntu-latest

    steps:
    #Scarica questa repo
    - name: Checkout
      uses: actions/checkout@v3
    #Fa il login su Docker Hub con delle secrets della repo
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    #Installa Buildx, plugin che estende le capacità del building di Docker Images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    #Costruisce l'immagine Docker e fa il push
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/formula1data:latest
